[FIX] mail: Fix validation error
Step to reproduce:
 1. Install documents in version 17.0.
 2. create new company for that create document folder and set alias_domain
 3. upgrade to 18.0  below menitoned traceback will raise

Issue:
  previously fix was deployed https://github.com/odoo/upgrade/commit/edae53792f81859dd4c843d8da4307e4eae8e0ff
  in the upgrade forcefully creating the incoming mails.

Cause:
    ``mail.alias.mixin`` is introduced in existing model
    https://github.com/odoo/enterprise/commit/a32825ee00f2b330d99113f4d8c1488903fe744e#diff-b394e0e6aa5c87ff7d84c0317fa2ed372a90b7d3e730c462fcb81d4b747f46ebL34
    As ``alias_id`` is kept as false according to this new alia records
    are creating but as it sudo it bringing all company records due to this
    and during upgrade env company alias_domain_id used which is letting alias_domain_id here
    https://github.com/odoo/odoo/blob/9719feb1fac64e06c988b336b077a0aa47a2b96a/addons/mail/models/mail_alias.py#L262
    of that company which is leading to validation error due to mismatch of record.

Fix:
  for fixing this is record have company_id so create mail alias
  according to that

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/18.0/odoo/service/server.py", line 1361, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-13>", line 2, in new
  File "/home/odoo/src/odoo/18.0/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/18.0/odoo/modules/registry.py", line 129, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/18.0/odoo/modules/loading.py", line 480, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "/home/odoo/src/odoo/18.0/odoo/modules/loading.py", line 365, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/18.0/odoo/modules/loading.py", line 206, in load_module_graph
    registry.init_models(env.cr, model_names, {'module': package.name}, new_install)
  File "/home/odoo/src/odoo/18.0/odoo/modules/registry.py", line 617, in init_models
    func()
  File "/home/odoo/src/odoo/18.0/addons/mail/models/mail_alias_mixin.py", line 49, in _init_column_alias_id
    alias = self.env['mail.alias'].sudo().create(record._alias_get_creation_values())
  File "<decorator-gen-136>", line 2, in create
  File "/home/odoo/src/odoo/18.0/odoo/api.py", line 495, in _model_create_multi
    return create(self, [arg])
  File "/home/odoo/src/odoo/18.0/addons/mail/models/mail_alias.py", line 266, in create
    return super().create(vals_list)
  File "<decorator-gen-120>", line 2, in create
  File "/home/odoo/src/odoo/18.0/odoo/api.py", line 496, in _model_create_multi
    return create(self, arg)
  File "/tmp/tmppqp1_15u/migrations/util/orm.py", line 249, in wrapper
    return f(*args, **kwargs)
  File "/tmp/tmppqp1_15u/migrations/base/0.0.0/pre-models-match_uniq.py", line 25, in create
    return super().create(vals_list)
  File "<decorator-gen-31>", line 2, in create
  File "/home/odoo/src/odoo/18.0/odoo/api.py", line 496, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/18.0/odoo/models.py", line 5017, in create
    records = self._create(data_list)
  File "/home/odoo/src/odoo/18.0/odoo/models.py", line 5275, in _create
    records._validate_fields(name for data in data_list for name in data['stored'])
  File "/home/odoo/src/odoo/18.0/odoo/models.py", line 1631, in _validate_fields
    check(self)
  File "/home/odoo/src/odoo/18.0/addons/mail/models/mail_alias.py", line 159, in _check_alias_domain_id_mc
    raise ValidationError(_(
odoo.exceptions.ValidationError: We could not create alias Inactive Alias because domain bsiri.co.th belongs to company BSIRI Company Limited (HeadOffice) while the owner document belongs to company MindGift LL>
```

upg-3017582
opw-4941387

closes odoo/odoo#219223

Signed-off-by: Thibault Delavallee (tde) <tde@openerp.com>